version: '3.4'
services:
  db:
    image: mariadb
    container_name: 'mariadb'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'dbrootpass'
      MOODLE_DATABASE: 'moodle'
      MOODLE_USER: 'moodleuser'
      MOODLE_DB_PASSWORD: 'moodlepass'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - moodledb:/var/lib/mysql

  moodleserver:
    depends_on:
      - db
    build: .
    container_name: 'moodleserver'
    restart: 'always'
    ports:
      - "80:80"
      - "443:443"
    environment:
      MOODLE_DB_HOST: db
      MYSQL_ROOT_PASSWORD: 'dbrootpass'
      MOODLE_DATABASE: 'moodle'
      MOODLE_USER: 'moodleuser'
      MOODLE_DB_PASSWORD: 'moodlepass'
    volumes:
      - ${PWD}:/var/www/html
      - moodledata:/var/www/moodledata 
    command:
      - bash
      - -c
      - |
        set -e
        echo 'running prestart script'
        /docker-init.sh
        echo 'initialization done, starting apache'
        exec /usr/sbin/apache2ctl -D FOREGROUND

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: 'phpmyadmin'
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - '8080:80'

volumes:
  moodledb:
  moodledata: